{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOVp/UylrNcn9Z0eLk8djv/",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/heronpaul312002-beep/CodeAlpha_ProjectName/blob/main/Midi.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 15,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "Ytn-1XY34Hve",
        "outputId": "3d1fd813-a782-4efc-cb72-e0d900e644a7"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n"
          ]
        }
      ],
      "source": [
        "from google.colab import drive\n",
        "drive.mount('/content/drive')"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install music21 tensorflow numpy"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "JWmL1KPr5n2I",
        "outputId": "fdd3a256-e1c2-4f6e-8461-3a47716a2958"
      },
      "execution_count": 16,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: music21 in /usr/local/lib/python3.12/dist-packages (9.9.2)\n",
            "Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.20.0)\n",
            "Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)\n",
            "Requirement already satisfied: chardet in /usr/local/lib/python3.12/dist-packages (from music21) (5.2.0)\n",
            "Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from music21) (1.5.3)\n",
            "Requirement already satisfied: jsonpickle in /usr/local/lib/python3.12/dist-packages (from music21) (4.1.1)\n",
            "Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from music21) (3.10.0)\n",
            "Requirement already satisfied: more-itertools in /usr/local/lib/python3.12/dist-packages (from music21) (10.8.0)\n",
            "Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from music21) (2.32.4)\n",
            "Requirement already satisfied: webcolors>=1.5 in /usr/local/lib/python3.12/dist-packages (from music21) (25.10.0)\n",
            "Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)\n",
            "Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)\n",
            "Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)\n",
            "Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)\n",
            "Requirement already satisfied: google_pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)\n",
            "Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)\n",
            "Requirement already satisfied: opt_einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)\n",
            "Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.2)\n",
            "Requirement already satisfied: protobuf>=5.28.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)\n",
            "Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)\n",
            "Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)\n",
            "Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)\n",
            "Requirement already satisfied: typing_extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)\n",
            "Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.2.0)\n",
            "Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.80.0)\n",
            "Requirement already satisfied: tensorboard~=2.20.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.20.0)\n",
            "Requirement already satisfied: keras>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.13.2)\n",
            "Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.16.0)\n",
            "Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)\n",
            "Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.47.0)\n",
            "Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (13.9.4)\n",
            "Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (0.1.0)\n",
            "Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (0.19.1)\n",
            "Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->music21) (3.4.7)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->music21) (3.15)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->music21) (2.5.0)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->music21) (2026.5.20)\n",
            "Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.10.2)\n",
            "Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (11.3.0)\n",
            "Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (0.7.2)\n",
            "Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.1.8)\n",
            "Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->music21) (1.3.3)\n",
            "Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->music21) (0.12.1)\n",
            "Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->music21) (4.63.0)\n",
            "Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->music21) (1.5.0)\n",
            "Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->music21) (3.3.2)\n",
            "Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->music21) (2.9.0.post0)\n",
            "Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.3)\n",
            "Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow) (4.2.0)\n",
            "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow) (2.20.0)\n",
            "Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow) (0.1.2)\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import os\n",
        "import glob\n",
        "import pickle\n",
        "import numpy as np\n",
        "from music21 import converter, instrument, note, chord, stream\n",
        "from tensorflow.keras.models import Sequential\n",
        "from tensorflow.keras.layers import LSTM, Dense, Dropout, Activation\n",
        "from tensorflow.keras.utils import to_categorical\n",
        "\n",
        "# ==============================================================================\n",
        "# PHASE 1: DATA COLLECTION & PREPROCESSING\n",
        "# ==============================================================================\n",
        "\n",
        "def get_notes_from_midi(midi_dir):\n",
        "    \"\"\" Parses a directory of MIDI files and extracts notes and chords. \"\"\"\n",
        "    notes = []\n",
        "\n",
        "    # Ensure you have a folder named 'midi_songs' filled with MIDI files (.mid)\n",
        "    if not os.path.exists(midi_dir) or len(os.listdir(midi_dir)) == 0:\n",
        "        raise FileNotFoundError(f\"Please create a '{midi_dir}' directory and add MIDI files.\")\n",
        "\n",
        "    print(\"Parsing MIDI files...\")\n",
        "    for file in glob.glob(os.path.join(midi_dir, \"*.mid\")):\n",
        "        try:\n",
        "            midi = converter.parse(file)\n",
        "            print(f\"Parsing: {file}\")\n",
        "\n",
        "            notes_to_parse = None\n",
        "            try: # Given files with multiple instrument parts\n",
        "                parts = instrument.partitionByInstrument(midi)\n",
        "                notes_to_parse = parts.parts[0].recurse()\n",
        "            except: # Given flat structures\n",
        "                notes_to_parse = midi.flat.notes\n",
        "\n",
        "            for element in notes_to_parse:\n",
        "                if isinstance(element, note.Note):\n",
        "                    notes.append(str(element.pitch))\n",
        "                elif isinstance(element, chord.Chord):\n",
        "                    # Represent chords by joining string integers of pitches with dots\n",
        "                    notes.append('.'.join(str(n) for n in element.normalOrder))\n",
        "        except Exception as e:\n",
        "            print(f\"Failed to parse {file}: {e}\")\n",
        "\n",
        "    return notes\n",
        "\n",
        "# ==============================================================================\n",
        "# PHASE 2: PREPARE SEQUENCES FOR TRAINING\n",
        "# ==============================================================================\n",
        "\n",
        "def prepare_sequences(notes, sequence_length=100):\n",
        "    \"\"\" Maps note strings to integers and builds input/output patterns. \"\"\"\n",
        "    # Get all unique pitch elements\n",
        "    pitches = sorted(list(set(notes)))\n",
        "    n_vocab = len(pitches)\n",
        "\n",
        "    # Create mapping dictionary to map pitches to integers\n",
        "    note_to_int = {note: num for num, note in enumerate(pitches)}\n",
        "\n",
        "    network_input = []\n",
        "    network_output = []\n",
        "\n",
        "    # Generate input sequences and their corresponding targeted next notes\n",
        "    for i in range(0, len(notes) - sequence_length):\n",
        "        sequence_in = notes[i:i + sequence_length]\n",
        "        sequence_out = notes[i + sequence_length]\n",
        "\n",
        "        network_input.append([note_to_int[char] for char in sequence_in])\n",
        "        network_output.append(note_to_int[sequence_out])\n",
        "\n",
        "    n_patterns = len(network_input)\n",
        "\n",
        "    # Reshape input pattern data into formats compatible with LSTM layers\n",
        "    # Shape: [samples, time steps, features]\n",
        "    network_input = np.reshape(network_input, (n_patterns, sequence_length, 1))\n",
        "\n",
        "    # Normalize input vector data\n",
        "    network_input = network_input / float(n_vocab)\n",
        "\n",
        "    # One-hot encode target output tracking arrays\n",
        "    network_output = to_categorical(network_output, num_classes=n_vocab)\n",
        "\n",
        "    return network_input, network_output, pitches, n_vocab\n",
        "\n",
        "# ==============================================================================\n",
        "# PHASE 3: BUILD THE DEEP LEARNING MODEL (LSTM)\n",
        "# ==============================================================================\n",
        "\n",
        "def create_network(network_input, n_vocab):\n",
        "    \"\"\" Structural architecture layout configurations of the LSTM network. \"\"\"\n",
        "    model = Sequential()\n",
        "\n",
        "    # Layer 1: LSTM layer to analyze input sequences\n",
        "    model.add(LSTM(256, input_shape=(network_input.shape[1], network_input.shape[2]), return_sequences=True))\n",
        "    model.add(Dropout(0.3)) # Prevents overfitting\n",
        "\n",
        "    # Layer 2: Second LSTM layer for deeper pattern abstraction\n",
        "    model.add(LSTM(256))\n",
        "    model.add(Dropout(0.3))\n",
        "\n",
        "    # Layer 3: Fully Connected Dense Layer mapping down to the categorical dimensions\n",
        "    model.add(Dense(n_vocab))\n",
        "    model.add(Activation('softmax')) # Outputs probability configurations\n",
        "\n",
        "    model.compile(loss='categorical_crossentropy', optimizer='rmsprop')\n",
        "    return model\n",
        "\n",
        "# ==============================================================================\n",
        "# PHASE 4: MUSIC SEED GENERATION\n",
        "# ==============================================================================\n",
        "\n",
        "def generate_notes(model, network_input, pitches, n_vocab, num_notes_to_gen=200):\n",
        "    \"\"\" Uses a trained model to generate a raw numerical note array sequence. \"\"\"\n",
        "    # Re-extract integer maps\n",
        "    note_to_int = {note: num for num, note in enumerate(pitches)}\n",
        "    int_to_note = {num: note for num, note in enumerate(pitches)}\n",
        "\n",
        "    # Pick a random starting point pattern from inputs as a composition seed\n",
        "    start = np.random.randint(0, len(network_input)-1)\n",
        "    pattern = list(network_input[start])\n",
        "    # Ensure it's a flat list of integers rather than scaled array vectors\n",
        "    pattern = [int(p * n_vocab) for p in pattern]\n",
        "\n",
        "    prediction_output = []\n",
        "\n",
        "    print(f\"Generating {num_notes_to_gen} notes...\")\n",
        "    for note_index in range(num_notes_to_gen):\n",
        "        prediction_input = np.reshape(pattern, (1, len(pattern), 1))\n",
        "        prediction_input = prediction_input / float(n_vocab)\n",
        "\n",
        "        # Query model predictive outputs\n",
        "        prediction = model.predict(prediction_input, verbose=0)\n",
        "        index = np.argmax(prediction) # Find index item matching highest probability\n",
        "\n",
        "        result = int_to_note[index]\n",
        "        prediction_output.append(result)\n",
        "\n",
        "        # Shift sequence window down by appending output and trimming the oldest entry\n",
        "        pattern.append(index)\n",
        "        pattern = pattern[1:]\n",
        "\n",
        "    return prediction_output\n",
        "\n",
        "# ==============================================================================\n",
        "# PHASE 5: CONVERT BACK TO MIDI & SAVE\n",
        "# ==============================================================================\n",
        "\n",
        "def save_midi(prediction_output, filename='output_song.mid'):\n",
        "    \"\"\" Re-encodes string tracking variables back down to MIDI tracks. \"\"\"\n",
        "    offset = 0\n",
        "    output_notes = []\n",
        "\n",
        "    # Reconstruct structural data streams\n",
        "    for pattern in prediction_output:\n",
        "        # Pattern represents a chord\n",
        "        if ('.' in pattern) or pattern.isdigit():\n",
        "            notes_in_chord = pattern.split('.')\n",
        "            notes = []\n",
        "            for current_note in notes_in_chord:\n",
        "                new_note = note.Note(int(current_note))\n",
        "                new_note.storedInstrument = instrument.Piano()\n",
        "                notes.append(new_note)\n",
        "            new_chord = chord.Chord(notes)\n",
        "            new_chord.offset = offset\n",
        "            output_notes.append(new_chord)\n",
        "        # Pattern represents a single isolated note\n",
        "        else:\n",
        "            new_note = note.Note(pattern)\n",
        "            new_note.offset = offset\n",
        "            new_note.storedInstrument = instrument.Piano()\n",
        "            output_notes.append(new_note)\n",
        "\n",
        "        # Adjust offsets cleanly so elements don't stack on top of each other\n",
        "        offset += 0.5\n",
        "\n",
        "    midi_stream = stream.Stream(output_notes)\n",
        "    midi_stream.write('midi', fp=filename)\n",
        "    print(f\"Success! Saved generated music to: {filename}\")\n",
        "\n",
        "# ==============================================================================\n",
        "# PIPELINE EXECUTION DRIVER ENTRYPOINT\n",
        "# ==============================================================================\n",
        "\n",
        "if __name__ == '__main__':\n",
        "    MIDI_FOLDER = \"/content/drive/MyDrive/midi_songs\"\n",
        "\n",
        "    # 1. Pipeline initialization\n",
        "    if not os.path.exists(MIDI_FOLDER):\n",
        "        os.makedirs(MIDI_FOLDER)\n",
        "        print(f\"Created a folder named '{MIDI_FOLDER}'. Drop your training .mid tracks into it, then run again.\")\n",
        "    else:\n",
        "        # Extract and parse\n",
        "        raw_notes = get_notes_from_midi(MIDI_FOLDER)\n",
        "\n",
        "        # Prepare tracking datasets\n",
        "        X, y, pitches, vocab_len = prepare_sequences(raw_notes)\n",
        "\n",
        "        # Initialize model layers\n",
        "        ai_model = create_network(X, vocab_len)\n",
        "\n",
        "        # Train model (using small epochs/batches as an initial baseline execution setup)\n",
        "        print(\"Training model...\")\n",
        "        ai_model.fit(X, y, epochs=15, batch_size=64)\n",
        "\n",
        "        # Generate new data patterns\n",
        "        generated_melody = generate_notes(ai_model, X, pitches, vocab_len)\n",
        "\n",
        "        # Map output structures\n",
        "        save_midi(generated_melody, 'generated_composition.mid')"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "R-ShXJjL58v3",
        "outputId": "c0ac222d-3929-47bf-aacb-45533bed1b34"
      },
      "execution_count": 25,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Parsing MIDI files...\n",
            "Parsing: /content/drive/MyDrive/midi_songs/youre only lonely L.mid\n",
            "Parsing: /content/drive/MyDrive/midi_songs/Queen - Bohemian Rhapsody.mid\n",
            "Parsing: /content/drive/MyDrive/midi_songs/Pirates of the Caribbean - He's a Pirate (3).mid\n",
            "Parsing: /content/drive/MyDrive/midi_songs/Never-Gonna-Give-You-Up-3.mid\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.\n",
            "  super().__init__(**kwargs)\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Training model...\n",
            "Epoch 1/15\n",
            "\u001b[1m11/11\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m15s\u001b[0m 1s/step - loss: 3.7061\n",
            "Epoch 2/15\n",
            "\u001b[1m11/11\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m19s\u001b[0m 967ms/step - loss: 3.3651\n",
            "Epoch 3/15\n",
            "\u001b[1m11/11\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m21s\u001b[0m 1s/step - loss: 3.3542\n",
            "Epoch 4/15\n",
            "\u001b[1m11/11\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m11s\u001b[0m 1s/step - loss: 3.3272\n",
            "Epoch 5/15\n",
            "\u001b[1m11/11\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m21s\u001b[0m 1s/step - loss: 3.3071\n",
            "Epoch 6/15\n",
            "\u001b[1m11/11\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m19s\u001b[0m 968ms/step - loss: 3.2929\n",
            "Epoch 7/15\n",
            "\u001b[1m11/11\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m22s\u001b[0m 1s/step - loss: 3.3142\n",
            "Epoch 8/15\n",
            "\u001b[1m11/11\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m19s\u001b[0m 943ms/step - loss: 3.1722\n",
            "Epoch 9/15\n",
            "\u001b[1m11/11\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m12s\u001b[0m 1s/step - loss: 3.2301\n",
            "Epoch 10/15\n",
            "\u001b[1m11/11\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m12s\u001b[0m 1s/step - loss: 3.1643\n",
            "Epoch 11/15\n",
            "\u001b[1m11/11\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m19s\u001b[0m 971ms/step - loss: 3.1818\n",
            "Epoch 12/15\n",
            "\u001b[1m11/11\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m12s\u001b[0m 993ms/step - loss: 3.1191\n",
            "Epoch 13/15\n",
            "\u001b[1m11/11\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m12s\u001b[0m 1s/step - loss: 3.0712\n",
            "Epoch 14/15\n",
            "\u001b[1m11/11\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m21s\u001b[0m 1s/step - loss: 3.0712\n",
            "Epoch 15/15\n",
            "\u001b[1m11/11\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m12s\u001b[0m 993ms/step - loss: 3.0262\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "/tmp/ipykernel_4030/2477234714.py:121: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)\n",
            "  pattern = [int(p * n_vocab) for p in pattern]\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Generating 200 notes...\n",
            "Success! Saved generated music to: generated_composition.mid\n"
          ]
        }
      ]
    }
  ]
}
